server:
#   port: ${CLUB_PORT:8080}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/club}


spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create